# Generated by Django 5.1.4 on 2026-03-22 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_troca_coins', models.PositiveIntegerField(default=500, help_text='Custo em coins para trocar de classe')),
            ],
            options={
                'verbose_name': 'Config — Troca de Classe',
                'verbose_name_plural': 'Config — Troca de Classe',
            },
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('guardian', 'Guardian'), ('analyst', 'Analyst'), ('sentinel', 'Sentinel'), ('hacker', 'Hacker')], max_length=20)),
                ('tipo', models.CharField(choices=[('xp_global', 'Bônus XP Global (%)'), ('xp_quiz', 'Bônus XP em Quiz (%)'), ('xp_decriptar', 'Bônus XP em Decriptar (%)'), ('xp_codigo', 'Bônus XP em Código (%)'), ('xp_password', 'Bônus XP em Cofre de Senhas (%)'), ('vida_extra', 'Vida Extra em Decriptar (+N)'), ('dica_gratis', 'Dica Gratuita por sessão'), ('streak_shield', 'Proteção de Streak (dias)'), ('coin_bonus', 'Bônus de Moedas (%)'), ('tentativa_extra', 'Tentativa Extra no Código (+N)')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor', models.FloatField(default=0, help_text='Percentual (10 = 10%) ou valor absoluto')),
                ('level_required', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perk',
                'verbose_name_plural': 'Perks',
                'ordering': ['classe', 'level_required'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='classe_trocada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('level_up', 'Level Up'), ('perk_unlock', 'Perk Desbloqueado'), ('conquista', 'Conquista'), ('missao', 'Missão Concluída'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField(blank=True)),
                ('icone', models.CharField(default='bi-bell-fill', max_length=50)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(choices=[('quiz', 'Quiz'), ('decriptar', 'Decriptar'), ('codigo', 'Código'), ('password', 'Cofre de Senhas'), ('feedback', 'Feedback'), ('conquista', 'Conquista'), ('missao', 'Missão'), ('bonus', 'Bônus')], max_length=20)),
                ('xp_base', models.IntegerField(default=0)),
                ('xp_bonus', models.IntegerField(default=0)),
                ('xp_total', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de XP',
                'verbose_name_plural': 'Histórico de XP',
                'ordering': ['-criado_em'],
            },
        ),
    ]
