# Generated by Django 5.1.4 on 2026-03-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_classeconfig_perk_player_classe_trocada_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfensivaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_tolerancia', models.PositiveSmallIntegerField(default=3, help_text='Quantos dias sem jogar antes de zerar a streak')),
                ('teto_bonus_ofensiva', models.PositiveSmallIntegerField(default=50, help_text='Limite máximo de % de bônus global vindo da ofensiva')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Config — Ofensiva',
                'verbose_name_plural': 'Config — Ofensiva',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='last_challenge_date',
            field=models.DateField(blank=True, help_text='Último dia em que completou pelo menos um desafio', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ofensiva',
            field=models.PositiveIntegerField(default=0, help_text='Total acumulado de ofensiva (sem teto)'),
        ),
    ]
