# Generated by Django 5.1.4 on 2026-03-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_ofensivaconfig_player_last_challenge_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.CharField(blank=True, help_text='Caminho relativo em static/ (ex: img/conquistas/nome.png)', max_length=200)),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('rara', 'Rara'), ('epica', 'Épica'), ('lendaria', 'Lendária')], default='comum', max_length=10)),
                ('trigger_type', models.CharField(choices=[('quiz_count', 'Nº de Quizzes concluídos'), ('quiz_perfect', 'Nº de Quizzes com 100%'), ('minigame_count', 'Nº de Minigames concluídos'), ('decriptar_count', 'Nº de Decriptar concluídos'), ('codigo_count', 'Nº de Código concluídos'), ('patrol_count', 'Nº de Patrulhas concluídas'), ('all_daily_count', 'Nº de dias com todos os desafios feitos'), ('level_reached', 'Level atingido'), ('streak_days', 'Streak de dias consecutivos'), ('ofensiva', 'Pontos de ofensiva'), ('xp_total', 'XP total acumulado'), ('shop_count', 'Nº de itens comprados na loja'), ('feedback_count', 'Nº de feedbacks enviados'), ('vulnerability', 'Reportou uma vulnerabilidade'), ('season_top1', 'Terminou temporada em 1º'), ('season_top3', 'Terminou temporada no Top 3')], max_length=20)),
                ('trigger_value', models.PositiveIntegerField(default=1, help_text='Valor necessário para desbloquear (ex: 5 quizzes)')),
                ('bonus_type', models.CharField(blank=True, choices=[('global_xp_pct', 'Bônus XP Global (%)'), ('quiz_xp_pct', 'Bônus XP em Quiz (%)'), ('minigame_xp_pct', 'Bônus XP em Minigames (%)'), ('patrol_xp_pct', 'Bônus XP em Patrulha (%)'), ('anagram_xp_pct', 'Bônus XP em Decriptar (%)'), ('termo_xp_pct', 'Bônus XP em Código (%)'), ('pw_xp_pct', 'Bônus XP em Cofre de Senhas (%)'), ('coin_pct', 'Bônus de Moedas (%)'), ('ofensiva_teto', 'Aumenta teto de ofensiva (+N)'), ('streak_shield', 'Proteção de streak (dias)')], max_length=20, null=True)),
                ('bonus_value', models.FloatField(default=0, help_text='Valor do bônus quando em destaque')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição no perfil')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'ordering': ['trigger_type', 'trigger_value'],
            },
        ),
        migrations.CreateModel(
            name='AchievementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_destaques', models.PositiveSmallIntegerField(default=5, help_text='Quantas conquistas em destaque aplicam bônus simultaneamente')),
            ],
            options={
                'verbose_name': 'Config — Conquistas',
                'verbose_name_plural': 'Config — Conquistas',
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueada_em', models.DateTimeField(auto_now_add=True)),
                ('em_destaque', models.BooleanField(default=True, help_text='Se True e dentro do limite, aplica o bônus')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='profiles.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Player',
                'verbose_name_plural': 'Conquistas dos Players',
                'ordering': ['-desbloqueada_em'],
                'unique_together': {('player', 'achievement')},
            },
        ),
    ]
