# Generated by Django 5.1.4 on 2026-03-31 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_achievement_achievementconfig_playerachievement'),
        ('rankings', '0002_season_rankingsnapshot'),
        ('store', '0004_alter_item_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePassConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battle_pass', to='rankings.season')),
            ],
            options={
                'verbose_name': 'Battle Pass — Config',
                'verbose_name_plural': 'Battle Pass — Configs',
            },
        ),
        migrations.CreateModel(
            name='BattlePassTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(help_text='Número do nível (1 a 50)')),
                ('xp_necessario', models.PositiveIntegerField(help_text='XP acumulado necessário para atingir este tier')),
                ('recompensa_tipo', models.CharField(choices=[('coins', 'Guardian Coins'), ('item', 'Item (Consumível/Passivo)'), ('cosmetico', 'Cosmético'), ('xp_bonus', 'Bônus de XP temporário')], max_length=15)),
                ('recompensa_coins', models.PositiveSmallIntegerField(default=0, help_text='Coins concedidos (se tipo = coins)')),
                ('recompensa_descricao', models.CharField(blank=True, help_text='Descrição legível da recompensa para o front', max_length=200)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='profiles.battlepassconfig')),
                ('recompensa_item', models.ForeignKey(blank=True, help_text='Item concedido (se tipo = item ou cosmetico)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_pass_tiers', to='store.item')),
            ],
            options={
                'verbose_name': 'Battle Pass — Tier',
                'verbose_name_plural': 'Battle Pass — Tiers',
                'ordering': ['tier'],
                'unique_together': {('battle_pass', 'tier')},
            },
        ),
        migrations.CreateModel(
            name='PlayerBattlePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_bp', models.PositiveIntegerField(default=0, help_text='XP acumulado especificamente no Battle Pass')),
                ('tier_atual', models.PositiveSmallIntegerField(default=0, help_text='Último tier desbloqueado')),
                ('tiers_coletados', models.JSONField(default=list, help_text='Lista de tiers já coletados pelo player')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='profiles.battlepassconfig')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Battle Pass do Player',
                'verbose_name_plural': 'Battle Pass dos Players',
                'unique_together': {('player', 'battle_pass')},
            },
        ),
    ]
