# Generated by Django 5.1.4 on 2026-04-01 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_battlepassconfig_battlepasstier_playerbattlepass'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('xp_gain', 'Ganho de XP'), ('xp_loss', 'Perda de XP'), ('level_up', 'Level Up'), ('coin_gain', 'Ganho de Moedas'), ('coin_loss', 'Perda de Moedas'), ('item_purchase', 'Compra de Item'), ('item_sell', 'Venda de Item'), ('item_activate', 'Ativação de Consumível'), ('store_reroll', 'Reroll da Loja'), ('achievement', 'Conquista Desbloqueada'), ('mission_claim', 'Missão Resgatada'), ('battle_pass', 'Recompensa Battle Pass'), ('classe_change', 'Troca de Classe'), ('system', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('xp_delta', models.IntegerField(default=0)),
                ('coin_delta', models.IntegerField(default=0)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log do Sistema',
                'verbose_name_plural': 'Logs do Sistema',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['player', '-criado_em'], name='profiles_sy_player__8212f9_idx')],
            },
        ),
    ]
