# Generated by Django 5.1.4 on 2026-04-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_systemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpevent',
            name='breakdown',
            field=models.JSONField(blank=True, default=list, help_text='Lista detalhada de bônus aplicados no cálculo'),
        ),
    ]
