# Generated by Django 5.1.4 on 2026-04-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_xpevent_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='classeconfig',
            name='custo_primeira_classe',
            field=models.PositiveIntegerField(default=0, help_text='Custo em coins para o player escolher a classe pela primeira vez'),
        ),
        migrations.AlterField(
            model_name='classeconfig',
            name='custo_troca_coins',
            field=models.PositiveIntegerField(default=500, help_text='Custo em coins para trocar de classe posteriormente'),
        ),
        migrations.AlterField(
            model_name='player',
            name='classe',
            field=models.CharField(choices=[('none', 'Sem Classe'), ('guardian', 'Guardian'), ('analyst', 'Analyst'), ('sentinel', 'Sentinel'), ('hacker', 'Hacker')], default='guardian', max_length=20),
        ),
    ]
