# Generated by Django 5.1.4 on 2026-04-03 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_classeconfig_custo_primeira_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recognition', '⭐ Reconhecimento'), ('infraction', '⚠️ Infração')], max_length=20)),
                ('xp_valor', models.PositiveIntegerField(help_text='Valor absoluto de XP (nunca negativo)')),
                ('descricao', models.CharField(max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_pontos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Pontos',
                'verbose_name_plural': 'Eventos de Pontos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
