# Generated by Django 5.1.4 on 2026-04-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_eventopontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='tipo',
            field=models.CharField(choices=[('xp_global', 'Bônus XP Global (%)'), ('xp_quiz', 'Bônus XP em Quiz (%)'), ('xp_decriptar', 'Bônus XP em Decriptar (%)'), ('xp_codigo', 'Bônus XP em Código (%)'), ('xp_password', 'Bônus XP em Cofre de Senhas (%)'), ('coin_bonus', 'Bônus de Moedas (%)'), ('add_time', 'Tempo Extra em Desafios (segundos)')], max_length=20),
        ),
    ]
