# Generated by Django 5.1.4 on 2026-04-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_refactor_perk_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_challenge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ofensiva',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
