# Generated by Django 5.1.4 on 2026-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_player_last_challenge_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='tipo',
            field=models.CharField(choices=[('xp_global', 'Bônus XP Global (%)'), ('xp_quiz', 'Bônus XP em Quiz (%)'), ('xp_decriptar', 'Bônus XP em Decriptar (%)'), ('xp_codigo', 'Bônus XP em Código (%)'), ('xp_password', 'Bônus XP em Cofre de Senhas (%)'), ('coin_bonus', 'Bônus de Moedas (%)'), ('add_time', 'Tempo Extra em Desafios (segundos)'), ('battle_pass', 'Battle Pass')], max_length=20),
        ),
    ]
