# Generated by Django 5.1.4 on 2026-05-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_systemlog_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='tipo',
            field=models.CharField(choices=[('xp_gain', 'XP Ganho'), ('xp_loss', 'XP Perdido'), ('level_up', 'Level Up'), ('classe_change', 'Troca de Classe'), ('achievement', 'Conquista Desbloqueada'), ('item_purchase', 'Compra de Item'), ('item_sell', 'Venda de Item'), ('item_activate', 'Ativação de Item'), ('store_reroll', 'Reroll da Loja'), ('coin_gain', 'Moedas Ganhas'), ('mission_claim', 'Missão Resgatada'), ('battle_pass', 'Battle Pass'), ('system', 'Sistema')], max_length=20),
        ),
    ]
