# Generated by Django 5.1.4 on 2026-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_systemlog_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpevent',
            name='fonte',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('decriptar', 'Decriptar'), ('codigo', 'Código'), ('password', 'Cofre de Senhas'), ('patrol', 'Patrulha'), ('feedback', 'Feedback'), ('conquista', 'Conquista'), ('missao', 'Missão'), ('bonus', 'Bônus')], max_length=20),
        ),
    ]
