# Generated by Django 5.1.4 on 2026-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_xpevent_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='bonus_type',
            field=models.CharField(blank=True, choices=[('global_xp_pct', 'Bônus XP Global (%)'), ('quiz_xp_pct', 'Bônus XP em Quiz (%)'), ('minigame_xp_pct', 'Bônus XP em Minigames (%)'), ('patrol_xp_pct', 'Bônus XP em Patrulha (%)'), ('anagram_xp_pct', 'Bônus XP em Decriptar (%)'), ('termo_xp_pct', 'Bônus XP em Código (%)'), ('pw_xp_pct', 'Bônus XP em Cofre de Senhas (%)'), ('coin_pct', 'Bônus de Moedas (%)'), ('ofensiva_teto', 'Aumenta teto de ofensiva (+N)'), ('streak_shield', 'Proteção de streak (dias)'), ('logscan_xp_pct', 'Bônus XP em LogScan (%)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='trigger_type',
            field=models.CharField(choices=[('quiz_count', 'Nº de Quizzes concluídos'), ('quiz_perfect', 'Nº de Quizzes com 100%'), ('minigame_count', 'Nº de Minigames concluídos'), ('decriptar_count', 'Nº de Decriptar concluídos'), ('codigo_count', 'Nº de Código concluídos'), ('patrol_count', 'Nº de Patrulhas concluídas'), ('all_daily_count', 'Nº de dias com todos os desafios feitos'), ('logscan_count', 'Nº de LogScan concluídos'), ('logscan_perfect', 'Nº de LogScan com 100%'), ('level_reached', 'Level atingido'), ('streak_days', 'Streak de dias consecutivos'), ('ofensiva', 'Pontos de ofensiva'), ('xp_total', 'XP total acumulado'), ('shop_count', 'Nº de itens comprados na loja'), ('feedback_count', 'Nº de feedbacks enviados'), ('vulnerability', 'Reportou uma vulnerabilidade'), ('season_top1', 'Terminou temporada em 1º'), ('season_top3', 'Terminou temporada no Top 3')], max_length=20),
        ),
    ]
