# Generated by Django 5.1.4 on 2026-07-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_perk_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='tipo',
            field=models.CharField(choices=[('global_xp_pct', 'Bônus XP Global (%)'), ('xp_quiz', 'Bônus XP em Quiz (%)'), ('xp_decriptar', 'Bônus XP em Decriptar (%)'), ('xp_codigo', 'Bônus XP em Código (%)'), ('xp_password', 'Bônus XP em Cofre de Senhas (%)'), ('xp_logscan', 'Bônus XP em LogScan (%)'), ('xp_patrol', 'Bônus XP em Patrulha Diária (%)'), ('vida_extra', 'Vida Extra em Decriptar (+N)'), ('dica_gratis', 'Dica Gratuita por sessão'), ('streak_shield', 'Proteção de Streak (dias)'), ('coin_bonus', 'Bônus de Moedas (%)'), ('tentativa_extra', 'Tentativa Extra no Código (+N)'), ('shop_discount', 'Desconto na Loja (%)'), ('ofensiva_teto', 'Aumento do Teto de Ofensiva (%)'), ('lexico_xp_pct', 'Bônus XP por Léxico Desbloqueado (% por palavra)')], max_length=20),
        ),
    ]
