# Generated by Django 5.1.4 on 2026-07-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_perk_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='trigger_type',
            field=models.CharField(choices=[('quiz_count', 'Nº de Quizzes concluídos'), ('quiz_perfect', 'Nº de Quizzes com 100%'), ('minigame_count', 'Nº de Minigames concluídos'), ('decriptar_count', 'Nº de Decriptar concluídos'), ('codigo_count', 'Nº de Código concluídos'), ('patrol_count', 'Nº de Patrulhas concluídas'), ('all_daily_count', 'Nº de dias com todos os desafios feitos'), ('logscan_count', 'Nº de LogScan concluídos'), ('logscan_perfect', 'Nº de LogScan com 100%'), ('level_reached', 'Level atingido'), ('streak_days', 'Streak de dias consecutivos'), ('ofensiva', 'Pontos de ofensiva'), ('xp_total', 'XP total acumulado'), ('lexico_count', 'Nº de léxicos descobertos'), ('shop_count', 'Nº de itens comprados na loja'), ('feedback_count', 'Nº de feedbacks enviados'), ('vulnerability', 'Reportou uma vulnerabilidade'), ('season_top1', 'Terminou temporada em 1º'), ('season_top3', 'Terminou temporada no Top 3')], max_length=20),
        ),
    ]
