# Generated by Django 5.1.4 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniGameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz'), ('anagram', 'Anagrama'), ('termo', 'Termo'), ('codebreaker', 'Codebreaker'), ('password', 'Montador de Senha')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('dados', models.JSONField()),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conteúdo de Minigame',
                'verbose_name_plural': 'Conteúdos de Minigames',
            },
        ),
    ]
