# Generated by Django 5.1.4 on 2026-03-16 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('minigames', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='minigamecontent',
            name='tipo',
            field=models.CharField(choices=[('anagram', 'Anagrama'), ('termo', 'Termo'), ('codebreaker', 'Codebreaker'), ('password', 'Montador de Senha')], max_length=20),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='0 = sem limite de tempo')),
                ('xp_reward', models.PositiveSmallIntegerField(default=200)),
                ('coin_reward', models.PositiveSmallIntegerField(default=20)),
                ('available_from', models.DateField(help_text='Data em que o quiz fica disponível')),
                ('available_days', models.PositiveSmallIntegerField(default=1, help_text='Por quantos dias o quiz ficará disponível')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes_criados', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='challenges.season')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-available_from'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('total_correct', models.PositiveSmallIntegerField(default=0)),
                ('abandoned', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('used_retake_token', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='minigames.quiz')),
            ],
            options={
                'verbose_name': 'Tentativa de Quiz',
                'verbose_name_plural': 'Tentativas de Quiz',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('xp_points', models.PositiveSmallIntegerField(default=50)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Permite múltiplas respostas corretas')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='minigames.quiz')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='minigames.quizquestion')),
            ],
            options={
                'verbose_name': 'Opção',
                'verbose_name_plural': 'Opções',
                'ordering': ['order'],
            },
        ),
    ]
