# Generated by Django 5.1.4 on 2026-03-17 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0002_alter_minigamecontent_tipo_quiz_quizattempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='available_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Por quantos dias o quiz ficará disponível'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='coin_reward',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=180, help_text='0 = sem limite de tempo'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='xp_reward',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='xp_points',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.CreateModel(
            name='PatrolAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('secret', models.CharField(max_length=4)),
                ('guesses', models.JSONField(default=list)),
                ('attempts_count', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('coins_earned', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de Patrulha',
                'verbose_name_plural': 'Tentativas de Patrulha',
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
