# Generated by Django 5.1.4 on 2026-03-17 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0003_alter_quiz_available_days_alter_quiz_coin_reward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordGameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_seconds', models.PositiveIntegerField(default=300, help_text='0 = sem limite')),
                ('xp_reward', models.PositiveSmallIntegerField(default=100)),
                ('coin_reward', models.PositiveSmallIntegerField(default=2)),
                ('rules_count_easy', models.PositiveSmallIntegerField(default=2)),
                ('rules_count_medium', models.PositiveSmallIntegerField(default=2)),
                ('rules_count_hard', models.PositiveSmallIntegerField(default=1)),
                ('active_days', models.CharField(default='0,1,2,3,4,5,6', help_text='Dias da semana separados por vírgula (0=Seg, 6=Dom)', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Config: Cofre de Senhas',
                'verbose_name_plural': 'Config: Cofre de Senhas',
            },
        ),
        migrations.CreateModel(
            name='PasswordAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_sequence', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_won', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('coins_earned', models.PositiveSmallIntegerField(default=0)),
                ('input_password', models.CharField(blank=True, max_length=500)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa: Cofre de Senhas',
                'verbose_name_plural': 'Tentativas: Cofre de Senhas',
                'ordering': ['-started_at'],
            },
        ),
    ]
