# Generated by Django 5.1.4 on 2026-03-21 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0004_passwordgameconfig_passwordattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='0 = sem limite')),
                ('xp_reward', models.PositiveSmallIntegerField(default=200)),
                ('coin_reward', models.PositiveSmallIntegerField(default=20)),
                ('word_length', models.PositiveSmallIntegerField(default=5, help_text='Comprimento da palavra (filtra banco automaticamente)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=6)),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('day_seg', models.BooleanField(default=False, verbose_name='Segunda-feira')),
                ('day_ter', models.BooleanField(default=True, verbose_name='Terça-feira')),
                ('day_qua', models.BooleanField(default=False, verbose_name='Quarta-feira')),
                ('day_qui', models.BooleanField(default=True, verbose_name='Quinta-feira')),
                ('day_sex', models.BooleanField(default=False, verbose_name='Sexta-feira')),
                ('day_sab', models.BooleanField(default=False, verbose_name='Sábado')),
                ('day_dom', models.BooleanField(default=False, verbose_name='Domingo')),
            ],
            options={
                'verbose_name': 'Config — Código',
                'verbose_name_plural': 'Config — Código',
            },
        ),
        migrations.CreateModel(
            name='DecriptarConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_seconds', models.PositiveIntegerField(default=0, help_text='0 = sem limite')),
                ('xp_per_word', models.PositiveSmallIntegerField(default=50)),
                ('coin_reward', models.PositiveSmallIntegerField(default=15)),
                ('words_count_easy', models.PositiveSmallIntegerField(default=2, verbose_name='Palavras fáceis / sessão')),
                ('words_count_medio', models.PositiveSmallIntegerField(default=2, verbose_name='Palavras médias / sessão')),
                ('words_count_hard', models.PositiveSmallIntegerField(default=1, verbose_name='Palavras difíceis / sessão')),
                ('max_lives', models.PositiveSmallIntegerField(default=3)),
                ('ativo', models.BooleanField(default=True)),
                ('day_seg', models.BooleanField(default=True, verbose_name='Segunda-feira')),
                ('day_ter', models.BooleanField(default=False, verbose_name='Terça-feira')),
                ('day_qua', models.BooleanField(default=False, verbose_name='Quarta-feira')),
                ('day_qui', models.BooleanField(default=False, verbose_name='Quinta-feira')),
                ('day_sex', models.BooleanField(default=True, verbose_name='Sexta-feira')),
                ('day_sab', models.BooleanField(default=False, verbose_name='Sábado')),
                ('day_dom', models.BooleanField(default=False, verbose_name='Domingo')),
            ],
            options={
                'verbose_name': 'Config — Decriptar',
                'verbose_name_plural': 'Config — Decriptar',
            },
        ),
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=30, unique=True)),
                ('dica', models.CharField(blank=True, max_length=300)),
                ('categoria', models.CharField(choices=[('ciberseguranca', 'Cibersegurança'), ('redes', 'Redes'), ('ti', 'Tecnologia da Informação'), ('politicas', 'Políticas e Compliance')], max_length=20)),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], max_length=10)),
                ('comprimento', models.PositiveSmallIntegerField(editable=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Palavra — Banco',
                'verbose_name_plural': 'Banco de Palavras',
                'ordering': ['dificuldade', 'comprimento', 'palavra'],
            },
        ),
        migrations.CreateModel(
            name='CodigoAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('secret_word', models.CharField(max_length=20)),
                ('guesses', models.JSONField(default=list)),
                ('won', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('coins_earned', models.PositiveSmallIntegerField(default=0)),
                ('abandoned', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_attempts', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.codigoconfig')),
            ],
            options={
                'verbose_name': 'Tentativa — Código',
                'verbose_name_plural': 'Tentativas — Código',
                'ordering': ['-date'],
                'unique_together': {('player', 'date', 'config')},
            },
        ),
        migrations.CreateModel(
            name='DecriptarAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('words_sequence', models.JSONField(default=list)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('lives_remaining', models.PositiveSmallIntegerField(default=3)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('coins_earned', models.PositiveSmallIntegerField(default=0)),
                ('abandoned', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decriptar_attempts', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.decriptarconfig')),
            ],
            options={
                'verbose_name': 'Tentativa — Decriptar',
                'verbose_name_plural': 'Tentativas — Decriptar',
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
