# Generated by Django 5.1.4 on 2026-03-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0005_codigoconfig_decriptarconfig_wordbank_codigoattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolattempt',
            name='remaining_seconds',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
