# Generated by Django 5.1.4 on 2026-03-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0006_patrolattempt_remaining_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrolattempt',
            name='remaining_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
