# Generated by Django 5.1.4 on 2026-04-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0007_alter_patrolattempt_remaining_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordattempt',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordattempt',
            name='timer_expired',
            field=models.BooleanField(default=False),
        ),
    ]
