# Generated by Django 5.1.4 on 2026-04-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0008_passwordattempt_abandoned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_attempts', models.PositiveSmallIntegerField(default=10, verbose_name='Máx. tentativas por rodada')),
                ('xp_base', models.PositiveSmallIntegerField(default=100, verbose_name='XP base')),
                ('coin_min', models.PositiveSmallIntegerField(default=10, verbose_name='Coins mínimo')),
                ('coin_max', models.PositiveSmallIntegerField(default=20, verbose_name='Coins máximo')),
                ('patrol_limit', models.PositiveSmallIntegerField(default=5, verbose_name='Limite de patrulhas (janela 7 dias)')),
            ],
            options={
                'verbose_name': 'Configuração da Patrulha',
                'verbose_name_plural': 'Configuração da Patrulha',
            },
        ),
    ]
