# Generated by Django 5.1.4 on 2026-04-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0009_patrolconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoconfig',
            name='dificuldade',
        ),
        migrations.RemoveField(
            model_name='codigoconfig',
            name='max_attempts',
        ),
        migrations.RemoveField(
            model_name='codigoconfig',
            name='word_length',
        ),
    ]
