# Generated by Django 5.1.4 on 2026-04-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0010_remove_codigoconfig_dificuldade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoattempt',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
