# Generated by Django 5.1.4 on 2026-04-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0011_codigoattempt_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordgameconfig',
            name='rules_count_insane',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
