# Generated by Django 5.1.4 on 2026-04-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0012_passwordgameconfig_rules_count_insane'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordgameconfig',
            name='rules_count_math',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
