# Generated by Django 5.1.4 on 2026-04-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0013_passwordgameconfig_rules_count_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoconfig',
            name='hint_time_penalty_pct',
            field=models.PositiveSmallIntegerField(default=15, help_text='Penalidade de tempo (%) ao usar dica'),
        ),
        migrations.AddField(
            model_name='decriptarconfig',
            name='hint_time_penalty_pct',
            field=models.PositiveSmallIntegerField(default=15, help_text='Penalidade de tempo (%) ao usar dica'),
        ),
    ]
