# Generated by Django 5.1.4 on 2026-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0014_codigoconfig_hint_time_penalty_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoattempt',
            name='free_hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codigoattempt',
            name='penalty_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decriptarattempt',
            name='free_hint_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decriptarattempt',
            name='penalty_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
