# Generated by Django 5.1.4 on 2026-04-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0015_codigoattempt_free_hint_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoattempt',
            name='bonus_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decriptarattempt',
            name='bonus_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordattempt',
            name='bonus_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='bonus_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
