# Generated by Django 5.1.4 on 2026-04-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0016_codigoattempt_bonus_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordattempt',
            name='penalty_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='penalty_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
