# Generated by Django 5.1.4 on 2026-04-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0017_add_penalty_seconds_quiz_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='coins_earned',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
