# Generated by Django 5.1.4 on 2026-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0018_quizattempt_coins_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoattempt',
            name='hint_penalty_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
