# Generated by Django 5.1.4 on 2026-04-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0019_codigoattempt_hint_penalty_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigoattempt',
            name='hint_penalty_seconds',
        ),
    ]
