# Generated by Django 5.1.4 on 2026-05-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0020_remove_codigoattempt_hint_penalty_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswerDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='minigames.quizattempt')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.quizoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.quizquestion')),
            ],
            options={
                'unique_together': {('attempt', 'question', 'option')},
            },
        ),
    ]
