# Generated by Django 5.1.4 on 2026-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0021_quizanswerdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbank',
            name='descricao_detalhada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
