# Generated by Django 5.1.4 on 2026-05-30 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0022_wordbank_descricao_detalhada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogScanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_seconds', models.PositiveIntegerField(default=180, help_text='0 = sem limite')),
                ('xp_per_word', models.PositiveSmallIntegerField(default=40)),
                ('coin_reward', models.PositiveSmallIntegerField(default=15)),
                ('words_count_easy', models.PositiveSmallIntegerField(default=2, verbose_name='Palavras fáceis / sessão')),
                ('words_count_medio', models.PositiveSmallIntegerField(default=2, verbose_name='Palavras médias / sessão')),
                ('words_count_hard', models.PositiveSmallIntegerField(default=1, verbose_name='Palavras difíceis / sessão')),
                ('ativo', models.BooleanField(default=True)),
                ('day_seg', models.BooleanField(default=False, verbose_name='Segunda-feira')),
                ('day_ter', models.BooleanField(default=True, verbose_name='Terça-feira')),
                ('day_qua', models.BooleanField(default=False, verbose_name='Quarta-feira')),
                ('day_qui', models.BooleanField(default=True, verbose_name='Quinta-feira')),
                ('day_sex', models.BooleanField(default=False, verbose_name='Sexta-feira')),
                ('day_sab', models.BooleanField(default=False, verbose_name='Sábado')),
                ('day_dom', models.BooleanField(default=False, verbose_name='Domingo')),
            ],
            options={
                'verbose_name': 'Config — LogScan',
                'verbose_name_plural': 'Config — LogScan',
            },
        ),
        migrations.CreateModel(
            name='LogScanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('grid', models.JSONField(default=list)),
                ('placements', models.JSONField(default=dict)),
                ('words_sequence', models.JSONField(default=list)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('xp_earned', models.PositiveSmallIntegerField(default=0)),
                ('coins_earned', models.PositiveSmallIntegerField(default=0)),
                ('abandoned', models.BooleanField(default=False)),
                ('timer_expired', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bonus_seconds', models.PositiveIntegerField(default=0)),
                ('penalty_seconds', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logscan_attempts', to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigames.logscanconfig')),
            ],
            options={
                'verbose_name': 'Tentativa — LogScan',
                'verbose_name_plural': 'Tentativas — LogScan',
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
