# Generated by Django 5.1.4 on 2026-05-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0023_logscanconfig_logscanattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='gabarito',
            field=models.TextField(blank=True, help_text='Explicação da resposta correta (exibida na galeria de treinamentos)'),
        ),
    ]
