# Generated by Django 5.1.4 on 2026-05-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0024_quiz_gabarito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='gabarito',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='gabarito',
            field=models.TextField(blank=True, help_text='Explicação da resposta correta (exibida na galeria de treinamentos)'),
        ),
    ]
