# Generated by Django 5.1.4 on 2026-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0025_remove_quiz_gabarito_quizquestion_gabarito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='xp_points',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
