# Generated by Django 5.1.4 on 2026-05-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0026_alter_quizquestion_xp_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='coin_reward',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
