# Generated by Django 5.1.4 on 2026-06-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0027_alter_quiz_coin_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='gabarito',
            field=models.TextField(blank=True, default=''),
        ),
    ]
