# Generated by Django 5.1.4 on 2026-03-27 18:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_common', models.PositiveSmallIntegerField(default=70, help_text='Probabilidade de aparecer um item Common nos slots da loja', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Peso COMMON (%)')),
                ('weight_rare', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Peso RARE (%)')),
                ('weight_epic', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Peso EPIC (%)')),
                ('slots_diarios', models.PositiveSmallIntegerField(default=4, help_text='Quantos itens aparecem na loja por dia')),
                ('reroll_custo_base', models.PositiveSmallIntegerField(default=5, help_text='Custo do primeiro reroll do dia (em G-Coins)')),
                ('reroll_incremento', models.PositiveSmallIntegerField(default=5, help_text='Quanto sobe o custo a cada reroll adicional no dia')),
                ('max_passivos_slots', models.PositiveSmallIntegerField(default=4, help_text='Quantos upgrades passivos o player pode ter ativos simultaneamente')),
                ('max_consumiveis', models.PositiveSmallIntegerField(default=20, help_text='Limite de consumíveis no inventário de carga')),
            ],
            options={
                'verbose_name': 'Config — Loja',
                'verbose_name_plural': 'Config — Loja',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveSmallIntegerField(help_text='ID canônico do JSON de design (ex: 1, 101, 201)', unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('consumable', 'Consumível'), ('passive', 'Upgrade Passivo'), ('cosmetic', 'Cosmético')], max_length=12)),
                ('raridade', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic')], default='COMMON', max_length=6)),
                ('build', models.CharField(choices=[('ECONOMY', 'Economy'), ('SPEEDRUN', 'Speedrun'), ('UTILITY', 'Utility'), ('SKILL', 'Skill'), ('SYNERGY', 'Synergy'), ('BUFF', 'Buff'), ('SOCIAL', 'Social'), ('RANKING', 'Ranking'), ('SCALING', 'Scaling'), ('SPECIFIC', 'Specific'), ('LUCK', 'Luck'), ('TIME', 'Time'), ('NONE', 'Nenhum')], default='NONE', max_length=10)),
                ('effect', models.CharField(choices=[('TOKEN_RETAKE', 'Refazer desafio falho'), ('XP_BOOST_DAYS', 'Bônus de XP por dias'), ('STREAK_CAP_BOOST', 'Aumenta teto de ofensiva'), ('STREAK_FREEZE', 'Congela streak por dias'), ('FREE_HINT', 'Dica grátis no próximo desafio'), ('EXTRA_LIFE_TIME', '+Tempo e +Vida no próximo desafio'), ('CONVERT_GOLD_XP', 'Converte Coins em XP'), ('CONVERT_XP_GOLD', 'Converte XP em Coins'), ('XP_PER_COIN', '+XP% por coin em saldo'), ('SHOP_DISCOUNT', 'Desconto na loja'), ('XP_LOW_CASH', '+XP% se saldo < 10'), ('XP_ODD_CASH', '+XP% se saldo ímpar'), ('TIME_REDUCTION_XP_BOOST', '-Tempo +XP%'), ('XP_PER_SECOND', '+XP% por segundo restante'), ('ADD_TIME', '+Tempo fixo'), ('XP_QUICK_WIN', '+XP% se vencer em < 3 tentativas'), ('XP_SAME_RARITY', '+XP% se todos 4 itens mesma raridade'), ('XP_PER_COMMON', '+XP% por item Common equipado'), ('XP_PER_EMPTY_SLOT', '+XP% por slot vazio'), ('XP_STACK_MULTIPLIER', 'Multiplica todos bônus XP'), ('XP_PER_COSMETIC', '+XP% por cosmético equipado'), ('XP_PER_FEATURED_ACHIEVEMENT', '+XP% por conquista em destaque'), ('XP_TOP_3', '+XP% se Top 3'), ('XP_OUTSIDE_TOP_10', '+XP% se fora do Top 10'), ('XP_PER_LEVEL', '+XP% por nível'), ('XP_CODE_CHALLENGE', '+XP% em desafios de Código'), ('XP_PATROL_CHALLENGE', '+XP% em desafios de Patrulha'), ('XP_DECRYPT_CHALLENGE', '+XP% em desafios de Decriptar'), ('XP_RANDOM', 'Bônus XP% aleatório'), ('DOUBLE_XP_WEEK_FIRST', 'Dobra XP do 1º desafio da semana'), ('COSMETIC_FRAME', 'Frame de perfil'), ('COSMETIC_BACKGROUND', 'Background de perfil'), ('COSMETIC_TITLE', 'Título de perfil')], max_length=40)),
                ('value', models.FloatField(default=0, help_text='Valor principal do efeito')),
                ('value_secondary', models.FloatField(default=0, help_text='Valor secundário (ex: xp_cost, time_mod)')),
                ('duration_days', models.PositiveSmallIntegerField(default=0, help_text='Duração em dias (0 = instantâneo)')),
                ('max_bonus', models.FloatField(default=0, help_text='Bônus máximo (0 = sem teto)')),
                ('cost', models.PositiveIntegerField(default=0, help_text='Preço base em G-Coins')),
                ('disponivel', models.BooleanField(default=True, help_text='Aparece na rolagem da loja')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(blank=True, help_text='Se preenchido, só aparece nessa temporada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_items', to='challenges.season')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['tipo', 'raridade', 'item_id'],
            },
        ),
        migrations.CreateModel(
            name='ActiveEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(max_length=40)),
                ('value', models.FloatField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('ativado_em', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_effects', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_instances', to='store.item')),
            ],
            options={
                'verbose_name': 'Efeito Ativo',
                'verbose_name_plural': 'Efeitos Ativos',
                'ordering': ['expires_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('purchase', 'Compra'), ('sell', 'Venda'), ('activate', 'Ativação de Consumível'), ('reroll', 'Reroll'), ('convert', 'Conversão (XP↔Coins)')], max_length=10)),
                ('coins_delta', models.IntegerField(default=0, help_text='Negativo = gasto, positivo = recebido')),
                ('xp_delta', models.IntegerField(default=0, help_text='XP ganho/perdido na transação')),
                ('desconto_aplicado', models.BooleanField(default=False)),
                ('descricao', models.CharField(blank=True, max_length=300)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação — Loja',
                'verbose_name_plural': 'Transações — Loja',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DailyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reroll_count', models.PositiveSmallIntegerField(default=0)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stores', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='daily_appearances', to='store.item')),
            ],
            options={
                'verbose_name': 'Loja Diária',
                'verbose_name_plural': 'Lojas Diárias',
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlayerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('slot_index', models.PositiveSmallIntegerField(blank=True, help_text='Slot ativo (1–4) para upgrades passivos. Null = não equipado', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('equipado', models.BooleanField(default=False, help_text='Para cosméticos: True = visual ativo no perfil')),
                ('adquirido_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='store.item')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do Player',
                'verbose_name_plural': 'Itens dos Players',
                'ordering': ['-adquirido_em'],
                'unique_together': {('player', 'item')},
            },
        ),
    ]
