# Generated by Django 5.1.4 on 2026-03-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_populate_item_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(default='bi-box', help_text='Classe do Bootstrap Icons (ex: bi-cpu-fill). Editável via admin.', max_length=60, verbose_name='Ícone Bootstrap Icons'),
        ),
    ]
