# Generated by Django 5.1.4 on 2026-04-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_item_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='raridade',
            field=models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=12),
        ),
    ]
