# Generated by Django 5.1.4 on 2026-04-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_item_raridade'),
        ('store', '0006_pacote_de_cargas'),
    ]

    operations = [
    ]
