# Generated by Django 5.1.4 on 2026-04-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_item_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='effect',
            field=models.CharField(choices=[('TOKEN_RETAKE', 'Refazer desafio falho'), ('XP_BOOST_DAYS', 'Bônus de XP por dias'), ('STREAK_CAP_BOOST', 'Aumenta teto de ofensiva'), ('STREAK_FREEZE', 'Congela streak por dias'), ('FREE_HINT', 'Dica grátis no próximo desafio'), ('EXTRA_LIFE_TIME', '+Tempo e +Vida no próximo desafio'), ('CONVERT_GOLD_XP', 'Converte Coins em XP'), ('CONVERT_XP_GOLD', 'Converte XP em Coins'), ('LOOT_PACK', 'Pacote de Cargas — drop aleatório de consumível'), ('XP_PER_COIN', '+XP% por coin em saldo'), ('SHOP_DISCOUNT', 'Desconto na loja'), ('XP_LOW_CASH', '+XP% se saldo < 10'), ('XP_ODD_CASH', '+XP% se saldo ímpar'), ('TIME_REDUCTION_XP_BOOST', '-Tempo +XP%'), ('XP_PER_SECOND', '+XP% por segundo restante'), ('ADD_TIME', '+Tempo fixo'), ('XP_QUICK_WIN', '+XP% se vencer em < 3 tentativas'), ('XP_SAME_RARITY', '+XP% se todos 4 itens mesma raridade'), ('XP_PER_COMMON', '+XP% por item Common equipado'), ('XP_PER_EMPTY_SLOT', '+XP% por slot vazio'), ('XP_STACK_MULTIPLIER', 'Multiplica todos bônus XP'), ('XP_PER_COSMETIC', '+XP% por cosmético equipado'), ('XP_PER_FEATURED_ACHIEVEMENT', '+XP% por conquista em destaque'), ('XP_TOP_3', '+XP% se Top 3'), ('XP_OUTSIDE_TOP_5', '+XP% se fora do Top 5'), ('XP_PER_LEVEL', '+XP% por nível'), ('XP_CODE_CHALLENGE', '+XP% em desafios de Código'), ('XP_PATROL_CHALLENGE', '+XP% em desafios de Patrulha'), ('XP_DECRYPT_CHALLENGE', '+XP% em desafios de Decriptar'), ('XP_RANDOM', 'Bônus XP% aleatório'), ('DOUBLE_XP_WEEK_FIRST', 'Dobra XP do 1º desafio da semana'), ('COSMETIC_FRAME', 'Frame de perfil'), ('COSMETIC_BACKGROUND', 'Background de perfil'), ('COSMETIC_TITLE', 'Título de perfil')], max_length=40),
        ),
    ]
