# Generated by Django 5.1.4 on 2026-04-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_item_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeritem',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
