# Generated by Django 5.1.4 on 2026-05-21 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_item_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfig',
            name='weight_legendary',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Peso LEGENDARY (%)'),
        ),
    ]
