# Generated by Django 5.1.4 on 2026-05-27 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('minigames', '0021_quizanswerdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWordUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_unlocks', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_unlocks', to='challenges.season')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='minigames.wordbank')),
            ],
            options={
                'verbose_name': 'Palavra Desbloqueada',
                'verbose_name_plural': 'Palavras Desbloqueadas',
                'ordering': ['-unlocked_at'],
                'unique_together': {('player', 'word', 'season')},
            },
        ),
    ]
