# Generated by Django 5.1.4 on 2026-05-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_rankingsnapshot_valor_desde'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerwordunlock',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_unlocks', to='rankings.season'),
        ),
    ]
