# Generated by Django 5.1.4 on 2026-03-22 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('ativa', models.BooleanField(default=False)),
                ('premio_descricao', models.TextField(blank=True, help_text='Descrição dos prêmios desta temporada')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('xp', 'XP — Experiência'), ('moedas', 'Moedas'), ('ofensiva', 'Ofensiva — Desafios completados')], max_length=15)),
                ('posicao', models.PositiveSmallIntegerField()),
                ('valor', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_snapshots', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='rankings.season')),
            ],
            options={
                'verbose_name': 'Snapshot de Ranking',
                'verbose_name_plural': 'Snapshots de Ranking',
                'ordering': ['posicao'],
                'unique_together': {('season', 'player', 'categoria')},
            },
        ),
    ]
