# Generated by Django 5.1.4 on 2026-04-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_season_rankingsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsnapshot',
            name='posicao_anterior',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
