# Generated by Django 5.1.4 on 2026-05-19 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_rankingsnapshot_posicao_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsnapshot',
            name='valor_desde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
