# Generated by Django 5.1.4 on 2026-03-16 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('tipo', models.CharField(choices=[('aviso', 'Aviso'), ('evento', 'Evento'), ('novidade', 'Novidade'), ('manutencao', 'Manutenção')], default='aviso', max_length=15)),
                ('fixado', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post do Admin',
                'verbose_name_plural': 'Posts do Admin',
                'ordering': ['-fixado', '-criado_em'],
            },
        ),
    ]
