# Generated by Django 5.1.4 on 2026-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='anexo',
            field=models.ImageField(blank=True, help_text='Apenas imagens (PNG, JPG, WEBP). Máx. 5MB.', null=True, upload_to='feedback_anexos/'),
        ),
    ]
