# Generated by Django 5.1.4 on 2026-03-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCoinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_sugestao_implementada', models.PositiveSmallIntegerField(default=2, verbose_name='Sugestão implementada')),
                ('coins_feedback_valido', models.PositiveSmallIntegerField(default=1, verbose_name='Feedback válido')),
                ('coins_bug_confirmado', models.PositiveSmallIntegerField(default=3, verbose_name='Bug confirmado')),
                ('coins_vulnerabilidade', models.PositiveSmallIntegerField(default=5, verbose_name='Vulnerabilidade confirmada')),
            ],
            options={
                'verbose_name': 'Config — Recompensas de Feedback',
                'verbose_name_plural': 'Config — Recompensas de Feedback',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='coin_reward',
            field=models.PositiveSmallIntegerField(default=0, help_text='Moedas a conceder ao player. Preenchido automaticamente ao marcar como resolvido.'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='coins_collected',
            field=models.BooleanField(default=False, verbose_name='Moedas coletadas pelo player'),
        ),
    ]
