# Generated by Django 5.1.4 on 2026-03-25 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description_template', models.CharField(help_text="Use {target} para inserir o valor dinâmico. Ex: 'Vença {target} partidas'", max_length=255)),
                ('category', models.CharField(choices=[('quiz', 'Quiz'), ('patrol', 'Patrulha (Codebreaker)'), ('password', 'Cofre de Senhas'), ('decrypt', 'Decriptar (Anagrama)'), ('code', 'Código (Termo)'), ('streak', 'Ofensiva'), ('any', 'Qualquer Desafio')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], max_length=10)),
                ('min_target', models.PositiveIntegerField(default=1)),
                ('max_target', models.PositiveIntegerField(default=5)),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('coin_reward', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMissionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_claimed', models.BooleanField(default=False, help_text='Se o prêmio do baú foi resgatado')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_sets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_generated', models.CharField(max_length=255)),
                ('target_value', models.PositiveIntegerField()),
                ('current_progress', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.missiontemplate')),
                ('mission_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='missions.usermissionset')),
            ],
        ),
    ]
