# Generated by Django 5.1.4 on 2026-03-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20260325_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontemplate',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
