# Generated by Django 5.1.4 on 2026-03-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_missiontemplate_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_xp', models.PositiveIntegerField(default=10)),
                ('reward_coins', models.PositiveIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Configuração de Missões',
                'verbose_name_plural': 'Configurações de Missões',
            },
        ),
    ]
