# Generated by Django 5.1.4 on 2026-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_missionconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontemplate',
            name='category',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('patrol', 'Patrulha (Codebreaker)'), ('password', 'Cofre de Senhas'), ('decrypt', 'Decriptar (Anagrama)'), ('code', 'Código (Termo)'), ('streak', 'Ofensiva'), ('feedback', 'Feedback e Sugestões'), ('any', 'Qualquer Desafio')], max_length=20),
        ),
    ]
