# Generated by Django 5.1.4 on 2026-03-16 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('ativa', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz'), ('anagram', 'Anagrama'), ('termo', 'Termo (Wordle)'), ('codebreaker', 'Codebreaker'), ('password', 'Montador de Senha')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=10)),
                ('xp_reward', models.PositiveSmallIntegerField(default=100)),
                ('coin_reward', models.PositiveSmallIntegerField(default=10)),
                ('data', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='challenges.season')),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='PlayerChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('tempo_gasto', models.PositiveSmallIntegerField(default=0)),
                ('concluido_em', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='challenges.challenge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desafio do Player',
                'verbose_name_plural': 'Desafios dos Players',
                'unique_together': {('player', 'challenge')},
            },
        ),
    ]
